// Auto-generated by inject_version_define.py - DO NOT EDIT
// Source: library.json

#ifndef USB_PD_CONTROLLER_VERSION_AUTOGEN_H
#define USB_PD_CONTROLLER_VERSION_AUTOGEN_H

#define WEB_MODULE_VERSION_STR "0.1.0"
#define WEB_MODULE_VERSION "0.1.0"

#endif // USB_PD_CONTROLLER_VERSION_AUTOGEN_H
